// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-S97OZFIakaPhOKpXxZxpmQKo6-S03Bw',
    appId: '1:81666312420:web:151f6f3cc99041018c04f1',
    messagingSenderId: '81666312420',
    projectId: 'voux39',
    authDomain: 'voux39.firebaseapp.com',
    storageBucket: 'voux39.firebasestorage.app',
    measurementId: 'G-7N4ML46WXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm8lAGHS_Yb-Vz5c85GjXjKxZm98ya6Js',
    appId: '1:81666312420:android:3edb24374fc7d8568c04f1',
    messagingSenderId: '81666312420',
    projectId: 'voux39',
    storageBucket: 'voux39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNBR0thTrnU1wfqPhhKd9_hVceU9_-E4',
    appId: '1:81666312420:ios:31377b6e3521c19f8c04f1',
    messagingSenderId: '81666312420',
    projectId: 'voux39',
    storageBucket: 'voux39.firebasestorage.app',
    iosClientId: '81666312420-m69mmsiahbcv71pceq4e8eeeem9gl05u.apps.googleusercontent.com',
    iosBundleId: 'com.omarkarimli.voux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYNBR0thTrnU1wfqPhhKd9_hVceU9_-E4',
    appId: '1:81666312420:ios:31377b6e3521c19f8c04f1',
    messagingSenderId: '81666312420',
    projectId: 'voux39',
    storageBucket: 'voux39.firebasestorage.app',
    iosClientId: '81666312420-m69mmsiahbcv71pceq4e8eeeem9gl05u.apps.googleusercontent.com',
    iosBundleId: 'com.omarkarimli.voux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-S97OZFIakaPhOKpXxZxpmQKo6-S03Bw',
    appId: '1:81666312420:web:d4b20f117e43ba398c04f1',
    messagingSenderId: '81666312420',
    projectId: 'voux39',
    authDomain: 'voux39.firebaseapp.com',
    storageBucket: 'voux39.firebasestorage.app',
    measurementId: 'G-MYHZ233CK5',
  );

}